spring:
  zipkin.baseUrl: zipkin:9411
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

server:
  port: 8072
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,gateway
